import "@/styles/globals.css";

import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { Providers } from "@/components/providers";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const nunito = Nunito({
	subsets: ["latin"],
	variable: "--font-nunito",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html className={`${nunito.variable}`} lang="en">
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
